### ISSUE TITLE
[Small fix] white splash screen on dark mode

### ISSUE THREAD

**Issue by oathzed** [iNPUTmice/Conversations#3979] opened 2021-01-26 00:23 UTC
This kind of kills the feel of dark mode. Can you make the splash screen dark by default?

https://imgur.com/a/ZlgbQpN

**Comment by iNPUTmice** [comment] 2021-01-26 06:12
Duplicate of your own issues? #3875 wtf

**Closed by iNPUTmice** 2021-01-26 06:12 UTC

**Comment by oathzed** [comment] 2021-01-26 19:51
> Duplicate of your own issues? #3875 wtf

Sorry about that :P
