### ISSUE TITLE
Search results enhancement

### ISSUE THREAD

**Issue by gjedeer** [iNPUTmice/Conversations#4051] opened 2021-03-29 09:16 UTC
When running a search, I often would like to see the surrounding messages. Long-touching the result and selecting "View conversation" takes me to the latest messages I exchanged with that person.

The only way to view context of the found message seems to be to remember the date, use View Conversation and scroll up until I find the date. That's rather suboptimal.

I just checked what Whatsapp does in this scenario - touching the search result opens the conversation, scrolls to the found message and the message is highlighted.

**Comment by iNPUTmice** [comment] 2021-03-29 09:18
duplicate of #3101

**Closed by iNPUTmice** 2021-03-29 09:18 UTC
