### ISSUE TITLE
Cue next sent message when the previous was a file upload which is still in progress

### ISSUE THREAD

**Issue by STPKITT** [iNPUTmice/Conversations#4340] opened 2022-07-16 09:59 UTC
When a user sends a message with a file upload the upload process can take some time, up to minutes. Currently while such an upload is still in progress and the user sents another message which is just text (or could also be another file) to the same contact Conversations will instantly sent it so that that message appears above the message containing the file which is still uploading. That can be confusing when you sent a file and the next message contains the context for that file. So IMO it would be better if Conversations would wait sending that second message until the file upload of the previous message is completed.

**Comment by licaon-kter** [comment] 2022-07-16 10:53
Keep picture order would be nice, now they are send as fast as they come, say if picture 3 is compressing...picture 4 5 6 would be sent first. Then again being blocked while a video is compressing for 3 minutes it's not fun :(

**Comment by STPKITT** [comment] 2022-07-17 15:32
Yeah exactly, good point since that situation underlines the issue in the current state. Conversations will currently upload all of let's say 10 pictures at once or at least several (I don't know the limit of parallel uploads or if there is any at all) which means a picture sent first could end up being completed after others which is bad when for example you're sending 10 photographed papers of a document which are supposed to be read one after the other.

**Comment by iNPUTmice** [comment] 2022-08-08 19:31
duplicate of #4224

**Closed by iNPUTmice** 2022-08-08 19:31 UTC
