### ISSUE TITLE
UX improvement: swiping

### ISSUE THREAD

**Issue by bertvandepoel** [iNPUTmice/Conversations#4317] opened 2022-05-05 09:16 UTC
A group of friends and I were discussing how we use conversations on a daily basis and how its UX could be improved (we were comparing it to other chat apps mostly). One of the things people remarked is that some swiping/gestures would much improve the flow of conversation. We were thinking of on the one hand swiping right to left on a specific message to quote it. I saw there were some previous issues and even a PR, but that that all went stale #3608 #4256 #3984 

One of us also remembered that in the past it was possible to use a swipe to exit a chat and bring back the overview screen of all chats. This would be great for a left to right swipe.

A combination of these two behaviours, would make it much more easy to both switch between different chats, and then quote-reply inside those chats.

**Comment by licaon-kter** [comment] 2022-05-05 09:19
Swipe to reveal was removed in Android as a gesture years ago, mostly because it would interfere with system gestures.

So not sure any swiping would tome back, but per message might be tackled in "next version" whenever that might come. :)

**Comment by licaon-kter** [comment] 2022-05-05 09:41
A mythical version 3, but we don't talk about that. :)

**Comment by bertvandepoel** [comment] 2022-05-05 09:43
Does that imply that it's being made behind closed doors? I looked for a separate repo or branch, but I don't see one/

**Comment by licaon-kter** [comment] 2022-05-05 10:02
No, yes, dunno, do join the support channel  just in case.

**Comment by bertvandepoel** [comment] 2022-05-05 10:13
Support channel?

**Comment by licaon-kter** [comment] 2022-05-05 10:20
https://github.com/iNPUTmice/Conversations#conversations-doesnt-work-for-me-where-can-i-get-help

**Comment by iNPUTmice** [comment] 2022-08-09 07:48
Duplicate of #4256

**Closed by iNPUTmice** 2022-08-09 07:48 UTC
