### ISSUE TITLE
Images sent from another client appear as text link and vice versa

### ISSUE THREAD

**Issue by anyuta1166** [iNPUTmice/Conversations#3860] opened 2020-08-12 15:03 UTC
#### General information

* **Version:** 2.8.10
* **Device:** Motorola G7 +
* **Android Version:**  Android 9 (stock)
* **Server name:** self hosted
* **Server software:** ejabberd 20.04
* **Conversations source:** PlayStore

Hmm... I use Xabber Web XMPP client to chat through the desktop sometimes.

And there is an issue with message history.

Images sent from Conversations appears as an image in Conversations, but as a text link in Xabber Web.
And vice versa.
Images sent from Xabber Web appears as an image in Xabber Web, but as a text link in Conversations.

What is this? Different implementation of XEP-0363: HTTP File Upload?

Any fix possible, and on which side it should be done?

**Comment by anyuta1166** [comment] 2020-08-12 15:28
I've checked and it seems that the messages containing images are sent in different formats.
This is from ejabberd archive table. Sorry, I don't know how to decode raw xml.

Conversations:

```
$fd1d985d-485e-48fe-a6e9-6e5827a3b7a2
$fd1d985d-485e-48fe-a6e9-6e5827a3b7a2jabber:x:oobxurl]https://jabber.vampik.ru:5443/upload/messag.i.ng/49e041908b8c3856767ba9fc5c95df68ae4b357e/wjqkr1IlxIL8SvH9nTVD9UJ9fMvp7r4lLnw110Vz/_R2YXUheSP6m6W5YJ6O3og.jpg]https://jabber.vampik.ru:5443/upload/messag.i.ng/49e041908b8c3856767ba9fc5c95df68ae4b357e/wjqkr1IlxIL8SvH9nTVD9UJ9fMvp7r4lLnw110Vz/_R2YXUheSP6m6W5YJ6O3og.jpg
```

Xabber:

```
ru/xabber-web-43821f1c$ec3e51c7-a486-40b0-8de5-d0221e8959c3urn:xmpp:reference:0	referencetypemediabegin0end154mediafile
media-type
image/jpegname4CxXWvCKRHuvt_wYT1aKHQ.jpgsize117502height853width1280uri[https://jabber.vampik.ru:5443/upload/vampik.ru/cddc0cac7c0f231d5dab8ad73a27f552bf903e9a/T6dPRk5pwncZDpq8pvx7Xtb0QId2yyh71BETocaY/4CxXWvCKRHuvt_wYT1aKHQ.jpg
$ec3e51c7-a486-40b0-8de5-d0221e8959c3#http://xabber.com/protocol/deliveryrequest[https://jabber.vampik.ru:5443/upload/vampik.ru/cddc0cac7c0f231d5dab8ad73a27f552bf903e9a/T6dPRk5pwncZDpq8pvx7Xtb0QId2yyh71BETocaY/4CxXWvCKRHuvt_wYT1aKHQ.jpg
```

**Comment by anyuta1166** [comment] 2020-08-12 16:30
It seems that you use XEP-0066: Out of Band Data, but Xabber uses more recent XEP-0372: References.

**Comment by anyuta1166** [comment] 2020-08-12 16:33
And Xabber developers said they would not support this old format: https://github.com/redsolution/xabber-web/issues/17#issuecomment-672922871

**Comment by iNPUTmice** [comment] 2020-08-12 19:46
Duplicate of #2637

It's worth pointing out that almost every other XMPP is compatible with Conversations (Converse.js, Dino, Gajim)

If you want to use Xabber you are locked into the Xabber ecosystem.

> If you want full compatibility on all platforms, use Xabber for Android or Xabber for iOS (due to release soon), they work seamlessly with each other.

**Closed by iNPUTmice** 2020-08-12 19:46 UTC

**Comment by anyuta1166** [comment] 2020-08-13 05:44
> It's worth pointing out that almost every other XMPP is compatible with Conversations (Converse.js, Dino, Gajim)
> 
> If you want to use Xabber you are locked into the Xabber ecosystem.

I just want to use an XMPP web client. Can you suggest one?

I tried to use Converse.js, but it has a fatal bug. It floods the archive database with the message receipts every time you open a chat with a person up to the point when archive retrieval is impossible. The bug was reported to developers, but they was not able to fix it in half a year. https://github.com/conversejs/converse.js/issues/1896

The only alternative I've found is Xabber Web. It works flawlessly except for embedded media (images, audio) and audio/video calls. As we discovered they use XEP-0372: References instead of XEP-0066: Out of Band Data for media transfer. Probably they use incompatible protocol for audio/video calls too. But now I'm not talking about it.

Why just you don't want to add support for XEP-0372: References to improve compatibility?

Repeating, I just want to use an XMPP web client - any XMPP web client - in addition to mobile application, for convenience. For example, for printing long messages from a desktop or sending some images without transferring them to the mobile phone beforehand.

**Comment by anyuta1166** [comment] 2020-08-13 05:52
That's the biggest flaw of XMPP. Tons of XEPs and everyone pulls the blanket over themselves supporting the set of XEPs they want and making incompatible applications :-(

**Comment by iNPUTmice** [comment] 2020-08-13 07:03
> Tons of XEPs and everyone pulls the blanket over themselves supporting the set of XEPs they want and making incompatible applications :-(

FWIW that is not entirely true. Most developers are in frequent talks with each other to maintain compatibility. It's just the Xabber devs who don’t give a shit.

SIMS will probably be implemented at some point but the XEP isn’t ready yet.

**Comment by anyuta1166** [comment] 2020-08-13 07:35
> It's just the Xabber devs who don’t give a shit.

Ok, got it.

Any suggestion on alternative XMPP web client?

**Comment by anyuta1166** [comment] 2020-08-14 15:38
To those who interested. I've made a fork of Xabber Web where I just disabled all incompatible features. So no files, images, voice messages sending and voice calls. But it is better than nothing. At least I have a text chat that works in a browser without installing any applications and doesn't flood my database :P
https://github.com/anyuta1166/xabber-web/tree/compat

**Comment by licaon-kter** [comment] 2020-08-14 16:05
@anyuta1166 so you've tested Converse HEAD as JC asked you and still not fixed?

**Comment by anyuta1166** [comment] 2020-08-14 16:11
@licaon-kter Will check it later and report the result. I need more spare time and a database backup. I'm tired of manually deleting message receipts from the database after each test.

**Comment by anyuta1166** [comment] 2020-08-14 16:17
BTW it has more bugs than just database flooding. Sometimes messages are not loaded from archive, and there was something else. I've not digged deeper yet due to the annoying message receipts bug.
Xabber Web just works out of the box (except incompatible features of course). It's a pity that such great developers decided to follow it's own way.

**Comment by licaon-kter** [comment] 2020-08-14 16:31
Converse HEAD has a lot of stuff fixed and added, I hope we get a release soon. Yes, not perfect but at least not incompatible like Xabber*
