### ISSUE TITLE
Feature Request: (HTTP File Upload) Recover real filename after download

### ISSUE THREAD

**Issue by ghost** [iNPUTmice/Conversations#2440] opened 2017-04-13 13:11 UTC
Currently, it is a very slow procedure to identify the files downloaded (on a file manager) because the random names.
Example: `8e0b97ec-4b7d-42ef-8036-3e05602df41f.txt` .
It isn't a problem with the pictures because of the thumbnails.

Is it possible to send the real filename in the body and after download the file, rename it?
Are there any other ideas?

**Comment by mimi89999** [comment] 2017-04-13 13:13
@participante0 AFAIK, Conversations never renames files. The real name is sent.

**Comment by Fank** [comment] 2017-05-28 05:54
@participante0 @mimi89999 i can confirm files which are uploaded still have the real name, so in xep 363 descriped.
Im using prosody backend.

**Comment by participante0** [comment] 2017-05-30 16:05
I received today `55e0b684-d7b7-4bbf-be50-bbaa28c5270a.pdf`
We (the sender and me) both have Conversations 1.18.4 and accounts in trashserver.net

**Comment by Fank** [comment] 2017-05-30 16:16
Add me and send me a file florian.kinder@fankserver.com

**Comment by licaon-kter** [comment] 2017-05-30 17:37
I can confirm this, a fix would be nice indeed.

**Comment by Fank** [comment] 2017-05-30 17:37
@licaon-kter contact me to validate it

**Comment by Fank** [comment] 2017-05-30 18:07
Ok guys nevermind same issue on prosody, the name just looks a little bit different

**Comment by Fank** [comment] 2017-05-30 18:21
Problem exists here: https://github.com/siacs/Conversations/blob/41b3df0d4394394dc7747c80224b3468da060626/src/main/java/eu/siacs/conversations/generator/IqGenerator.java#L332

the `convertFilename` changes the filename to an url friendly one

**Comment by Fank** [comment] 2017-05-31 14:28
@iNPUTmice could we remove the base64 encode? and just replace non url friendly characters with nothing?

**Comment by knoy** [comment] 2017-06-01 15:16
This is a pretty serious UI problem for file transfer and when you have hundreds of files sent (especially when dealing with multiple revisions of the same file) it makes finding the correct file extremely difficult. If this could be fixed would make file transfer a lot better

**Comment by knoy** [comment] 2017-06-01 15:17
Perhaps https://developer.android.com/reference/java/net/URLEncoder.html would be more appropriate than base64 to preserve readability

**Comment by WarrenBKN** [comment] 2017-07-14 02:31
An option to save them as name

YYMMDD_sequencenum

would be better for me

**Comment by kriztan** [comment] 2017-09-22 07:53
You could take a look at my changes to my Conversationis fork. I'm using the date and the last 4 chars from message UUID. This helps a lot, the sent and received files are sorted time based. 
https://github.com/kriztan/Pix-Art-Messenger/blob/master/src/main/java/de/pixart/messenger/http/HttpDownloadConnection.java#L97

**Comment by iNPUTmice** [comment] 2020-05-24 08:56
Duplicate of #1747

**Closed by iNPUTmice** 2020-05-24 08:56 UTC
