### ISSUE TITLE
RFCs and XEPs support page with VERSION

### ISSUE THREAD

**Issue by Neustradamus** [iNPUTmice/Conversations#3932] opened 2020-11-27 09:54 UTC
Currently we do not know what is the XEP-XXXX vX.X.X supported in Conversations.

It is possible to add RFCs and XEPs with version (XEP-XXXX v1.2)?
- https://conversations.im/
- https://github.com/iNPUTmice/Conversations/blob/master/README.md
- https://github.com/siacs/Conversations/blob/master/docs/XEPs.md

Base:
- RFCXXXX
- XEP-XXXX v1.2

Examples:
- https://github.com/UWPX/UWPX-Client/blob/master/README.md
- https://github.com/telldus/xmppjs-client-plugins/blob/master/README.md
- https://github.com/ortuman/jackal/blob/master/README.md
- https://profanity-im.github.io/xeps.html
- https://metronome.im/supported-xeps-list
- https://dev.gajim.org/gajim/gajim/wikis/help/GajimXEPSupport
- https://github.com/jappix/jappix/blob/master/PROTOCOL.md

Thanks in advance.

Linked to:
- https://github.com/iNPUTmice/Conversations/issues/2879

**Comment by licaon-kter** [comment] 2020-11-27 09:56
https://github.com/iNPUTmice/Conversations/blob/master/doap.rdf ?

**Comment by Neustradamus** [comment] 2020-11-27 10:16
@licaon-kter: Thanks but currently, it is not easy to read...

It is not in:
- README.md
- XEPs.md

**Comment by licaon-kter** [comment] 2020-11-27 10:29
Maybe this needs a proper page on conversations.im like Gajim has

**Comment by iNPUTmice** [comment] 2020-11-27 11:04
duplicate of #2879

**Closed by iNPUTmice** 2020-11-27 11:04 UTC
