### ISSUE TITLE
Send "mute" session-info when video/audio is disabled in a call

### ISSUE THREAD

**Issue by fiaxh** [iNPUTmice/Conversations#4086] opened 2021-05-13 11:44 UTC
Please send a "mute" session-info when video or audio are (temporarily) disabled in a call: https://xmpp.org/extensions/xep-0167.html#info-mute. That way, other clients know that their counterpart disabled audio/video and can use that information to adjust their UI.

**Comment by iNPUTmice** [comment] 2021-05-13 11:47
duplicate of #4068

**Closed by iNPUTmice** 2021-05-13 11:47 UTC
