### ISSUE TITLE
Set xml:lang according to the system language

### ISSUE THREAD

**Issue by mdosch** [iNPUTmice/Conversations#3815] opened 2020-07-01 13:31 UTC
It would be nice if you set `xml:lang` according to [RFC6210 Section 4.7.4](https://tools.ietf.org/html/rfc6120#section-4.7.4) to the system language. That would enable services/bots to reply in the users native language.

**Comment by iNPUTmice** [comment] 2020-07-01 13:37
duplicate of #3804

**Closed by iNPUTmice** 2020-07-01 13:37 UTC
