### ISSUE TITLE
Feature request: Open Graph Protocol previews

### ISSUE THREAD

**Issue by hololeap** [iNPUTmice/Conversations#3997] opened 2021-02-13 18:00 UTC
A [nice feature that I have seen in the Steam chat client](https://steamcommunity.com/updates/chatupdate) is the ability to show a preview for links and the option to play media links directly in the client. I've been looking for a standard for this, and [Open Graph Protocol](https://ogp.me/) is the best I can find. This isn't a critical feature or anything, but I wanted to bring it up to see how other people felt about it.

**Comment by iNPUTmice** [comment] 2021-02-13 18:37
duplicate of #1778

**Closed by iNPUTmice** 2021-02-13 18:37 UTC
