### ISSUE TITLE
(Feature request) Create an audio section on chat actions.

### ISSUE THREAD

**Issue by hardBSDk** [iNPUTmice/Conversations#4378] opened 2022-09-10 04:30 UTC
Implement a new option "Choose audio" where it open a list of recent audio files (timestamp saved order).

**Comment by licaon-kter** [comment] 2022-09-10 04:37
Your file selector has a "recent" section and an "audio" section.

/close as duplicate of your other audio issue

**Closed** 2022-09-10 05:33 UTC
