### ISSUE TITLE
Feature Request:  Auto-reconnect webrtc session when network is changed.

### ISSUE THREAD

**Issue by dingdongnigetou** [iNPUTmice/Conversations#3729] opened 2020-05-14 02:42 UTC
Network changed case:
* WIFI->Cellular or WIFI->WIFI or Cellular->WIFI
* The public IP of Cellular-Network is changed

For more stable, we should consider this issue.

**Comment by iNPUTmice** [comment] 2020-05-14 06:34
duplicate of #3719

**Closed by iNPUTmice** 2020-05-14 06:34 UTC
